variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build
before_script:
  - sudo n 12
  - sudo chown -R gitlab-runner:gitlab-runner .
after_script:
  - sudo chown -R gitlab-runner:gitlab-runner .
latest-build:
  stage: build
  script:
    - set -a
    - source $DEVELOPMENT_SERVER_ENV
    - set +a
    - ~/bin/buildfrontend.sh $CI_COMMIT_REF_NAME "git lfs install 2>&1 || true; git lfs pull; yarn && yarn build --silent"
  tags:
    - docker
    - build
  only:
    refs:
      - master
stable-build:
  stage: build
  script:
    - set -a
    - source $PRODUCTION_SERVER_ENV
    - set +a
    - ~/bin/buildfrontend.sh $CI_COMMIT_REF_NAME "git lfs install 2>&1 || true; git lfs pull; yarn && yarn build --silent"
  tags:
    - docker
    - build
  only:
    refs:
      - stable